name: Terraform Azure

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: terraform-${{ github.ref }}
  cancel-in-progress: true
jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ACTIONS_STEP_DEBUG: true
      TF_LOG: DEBUG
      TF_IN_AUTOMATION: "true"
      ARM_CLIENT_ID: "1cfde4b6-8395-4089-aef6-b71f83fb029e"
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Terraform
        uses: actions/cache@v3
        with:
          path: ~/.terraform
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="storage_account_name=${{ secrets.TF_STATE_SA }}" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=aks-kafka.tfstate"

      - name: Terraform Plan
        run: terraform plan -out=tfplan -parallelism=5
        timeout-minutes: 10

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve tfplan
